plugins {
    id "java-library"
}

dependencies {
    api project(":common:domain")

    implementation "org.snakeyaml:snakeyaml-engine:${snakeyaml_engine_version}"
    implementation "com.google.code.gson:gson:${gson_version}"

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}