plugins {
    id "java-library"
}

dependencies {
    implementation "net.kyori:adventure-text-minimessage:${adventure_version}"
    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}
